Warning: Permanently added '172.31.68.105' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.64.103' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.69.211' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.65.132' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.71.13' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.73.235' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.77.77' (ECDSA) to the list of known hosts.
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:295: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[:,0,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:295: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[:,0,:]*mag0/magF,
[ip-172-31-74-184:11554] 7 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[ip-172-31-74-184:11554] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[ip-172-31-74-184][[49120,1],0][btl_tcp_endpoint.c:803:mca_btl_tcp_endpoint_complete_connect] connect() to 172.31.77.77 failed: Connection refused (111)
